### PR TITLE
Initialize `global` and `path` fields of `globalPkg`

### PR DESCRIPTION
**Pull request by pofl**

### CODE REVIEW

**Comment by pofl** [comment]
I am hunting a bug and this PR was my first attempt for a fix, but it didn't fix it.

My proto file looks something like this 

```
syntax = "proto3";

option java_package = "tracking.event";
option go_package = ".;events";

message _BaseInfo {
        string id = 1;
}

message AccountCreated {
    _BaseInfo base_info = 1;
}
```

If I run schema-gen on it it fails with errormsg 
```
--bq-schema_out: Failed to convert events.proto: no such package found: 
```
Looks like schema-gen requires a package (which it shouldn't). And if I add a package in the proto file then protoc runs without errors but no files are generated. 
@chuhlomin any ideas how to proceed?

**Comment by chuhlomin** [comment]
I think plugin needs package there in order to work. Also, you need to specify `table_name` custom option:
```proto
syntax = "proto3";

package foo;

option java_package = "tracking.event";
option go_package = ".;events";

import "bq/bq_table.proto";

message _BaseInfo {
  string id = 1;
}

message AccountCreated {
  option (gen_bq_schema.bigquery_opts).table_name = "account_created";

  _BaseInfo base_info = 1;
}
```
will result in `account_created.schema` file:
```json
[
 {
  "name": "base_info",
  "type": "RECORD",
  "mode": "NULLABLE",
  "fields": [
   {
    "name": "id",
    "type": "STRING",
    "mode": "NULLABLE"
   }
  ]
 }
]
```

**Comment by pofl** [comment]
Okay, yeah the docs are actually pretty clear about the fact that the table name is necessary 🤦 

Still, since the proto standard doesn't require a package AFAIK, shouldn't this plugin be able to work without them? Or maybe a workaround would be to assume a default package name if none is specified.

**Comment by chuhlomin** [comment]
You right! Plugin should work with messages without package (meaning "global" package).
I fixed that in #4 and released version [1.6](https://github.com/chuhlomin/protoc-gen-bq-schema/releases/tag/1.6), please confirm.

**Comment by pofl** [comment]
LGTM! Thank you

**Pull request closed without merging**
